name: Go

on:
  push:
    branches: [ "main" ]
    paths-ignore:
       - "**.md"
       - "LICENSE"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
       - "**.md"
       - "LICENSE"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.49

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
